### ISSUE TITLE
removeTone('zi') → false

### ISSUE THREAD

**Issue by agj** [pepebecker/pinyin-utils#1]
Hello! I've been finding your pinyin-utils really useful, but today I ran into one small issue:

If you attempt to remove a fifth/neutral tone with `removeTone()`, it returns `false`, which is rather unhelpful in my use case. Is this by design, for some reason?

```js
require('pinyin-utils').removeTone('zi') //=> false
require('pinyin-utils').removeTone('zi5') //=> false
```

**Comment by pepebecker** [comment]
Hi @agj, this was not intended!

I was going to fix this but then I saw that you are already working on a fork.
Do you want to make pull request?

**Comment by agj** [comment]
Hey. I can send you a PR, but if you check my fork you'll see I've made a few other changes. I particularly revamped the tests to not check for a few cases but actually check most valid Mandarin syllables against a table, and added support for standalone 'n' and 'm' as syllables as well (like in 嗯 and 呣). I made these changes to suit my own needs, so you tell me if you want them.

**Comment by agj** [comment]
Nevermind, I see you grabbed the changes!

**Comment by pepebecker** [comment]
@agj sorry, I needed the changes urgently. You can PR and add yourself as a contributor to the `package.json`

**Comment by agj** [comment]
Yeah, don't sweat it! Sure, I might do it when I get the chance.
