### ISSUE TITLE
Breaking changes in minor version change?

### ISSUE THREAD

**Issue by benlieb** [pepebecker/pinyin-utils#12]
Thanks for your work in making this package available. 

I recently did yarn upgrade and found that my pinyin-utils changed from 1.61.0 to 1.74.0. This should be allowed because my `package.json` file has the package listed as:

```
"pinyin-utils": "^1.61.0",
```

The caret means that minor version upgrades are allowed, since they don't introduce breaking changes. But in this case it seems that the default export had been removed from the library and my code wouldn't transpile so it appears that a breaking change was introduced in a minor version which goes agains semver. 

If it is true that these changes are breaking changes, could I ask that you consider increasing the major version when this happens so that the code matches the expectations of semver?

Thanks a lot! And thanks again for your work!

**Comment by pepebecker** [comment]
I increased the version to `2.0.0`.
Sorry for the inconvenience
